#
# Makefile--
#    Makefile for storage/ermia
#
# IDENTIFICATION
#    src/backend/storage/ermia/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/storage/ermia
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = pg_ermia.o

include $(top_srcdir)/src/backend/common.mk
