DROP DATABASE IF EXISTS mfpr;
CREATE DATABASE mfpr;
CREATE TABLE mfpr.test0 (
    k1 INT(11) NOT NULL DEFAULT 0,
    k2 VARCHAR(256) NOT NULL DEFAULT 0,
PRIMARY KEY (`k1`, `k2`)) ENGINE = ERMIA; 
BEGIN;
INSERT INTO mfpr.test0 (k1, k2) VALUES (1, "A SHORT STRING");
SELECT COUNT(*) FROM mfpr.test0;
-- TEST 1: This insert should succeed.
INSERT INTO mfpr.test0 (k1, k2) VALUES (1, "A VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGA VERY LONG STRINGPADD");
-- TEST 2: Should see ONLY two record with different values.
SELECT COUNT(*) FROM mfpr.test0;
-- TEST 3: Should see ONLY two record with different values.
SELECT COUNT(*) FROM mfpr.test0 WHERE k1 = 1;
COMMIT;
